deepforge-dev/deepforge

- config/components.json
- config/config.dev.js
- config/config.webgme.js
- package.json
- src/visualizers/Visualizers.json
- webgme-setup.json
WIP #18 set the layout to npm release
Added breadcrumbheader, autoviz. WIP #18
> Fixes #18 Added simple UI (w/ dev mode)

- .travis.yml
- README.md
> Added travis config. Fixes #22

- src/plugins/ImportTorch/lua.js
- test/test-cases/code/alexnetowtbn.lua
- test/test-cases/code/vgg.lua
Switched test-cases to scientific notation. WIP #30
> Updated dependency to support compiling lua w/ sci notation. Fixes #30

- package.json
- src/plugins/CreateTorchMeta/CreateTorchMeta.js
- src/plugins/CreateTorchMeta/metadata.json
- src/plugins/GenerateArchitecture/GenerateArchitecture.js
- src/plugins/GenerateArchitecture/metadata.json
- src/plugins/GenerateYaml/GenerateYaml.js
- src/plugins/GenerateYaml/metadata.json
- src/plugins/ImportTorch/ImportTorch.js
- src/plugins/ImportTorch/metadata.json
- src/plugins/ImportYaml/ImportYaml.js
- src/plugins/ImportYaml/metadata.json
- test/globals.js
- test/plugins/CreateTorchMeta/CreateTorchMeta.spec.js
- test/plugins/ExecutePipeline/ExecutePipeline.js
- test/plugins/GenerateArchitecture/GenerateArchitecture.spec.js
- test/plugins/GenerateYaml/GenerateYaml.spec.js
- test/plugins/ImportTorch/ImportTorch.spec.js
- test/plugins/ImportYaml/ImportYaml.spec.js
- test/utils/utils.spec.js
WIP #49 Updated plugins to v2.0.0 structure
WIP #49 Updated webgme version
> Fixes #49 Updated webgme dependency to v2.x

- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
WIP #89 Added check for added nodes
WIP #89 Updated territory to contain all operations in meta
> Fixes #89 Updated territory and added nodes

- src/plugins/CreateExecution/CreateExecution.js
Also fixed executing empty pipelines
> Added execution dir detection. Fixes #125

- src/plugins/ExecutePipeline/ExecutePipeline.js
- src/plugins/ExecutePipeline/templates/deserialize.ejs
- src/plugins/ExecutePipeline/templates/serialize.ejs
WIP #134. Updated templates
WIP #134 Added filepath to template contents
> Fixes #134. Updated ser/deser to be given 'path' to save to/read from

- src/plugins/ExecutePipeline/ExecutePipeline.js
WIP #132 Added name change w/ metadata... Not fixing zip file
WIP #132 Updated renaming to use metadata (no more dl-ing data!)
WIP #132. Chaining operations works!
WIP #132. Removed unneeded comments
> Fixes #132 Added efficient data handling in the browser

- src/common/viz/PipelineControl.js
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
- src/visualizers/widgets/PipelineEditor/PipelineEditorWidget.js
WIP #177 Added button
Added necessary callbacks to mixin WIP #177
WIP #177. Added PipelineWidget to use callbacks from mixin
> Added op creation to fab. Fixes #177

- src/common/viz/PipelineControl.js
- src/decorators/OperationDecorator/EasyDAG/OperationDecorator.EasyDAGWidget.js
- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
- src/visualizers/panels/PipelineEditor/PipelineEditorPanel.js
- src/visualizers/widgets/PipelineEditor/Connection.js
- src/visualizers/widgets/PipelineEditor/OperationNode.js
- src/visualizers/widgets/PipelineEditor/PipelineEditorWidget.js
- src/visualizers/widgets/PipelineEditor/SelectionManager.js
WIP #178 Moved delete button to top left
WIP #178 Added basic port rendering
WIP #178 Added labels for ports and fixed input pos's
WIP #178 Added support for connecting op ports
WIP Made PipelineEditor embedded
WIP #178 Added conn deletion
WIP #178 Fixed backwards connecting
WIP #178. Remove port opts that would create a cycle
WIP #178 Added single node delete
WIP #178 Updated connections to ports and removed create btn
WIP #178 Fixed port color on change
> Added support for ports in PipelineEditor Fixes #178

- package.json
- src/visualizers/panels/ArchEditor/ArchEditorPanel.js
- src/visualizers/panels/ExecutionView/ExecutionViewPanel.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
WIP #195 Added onNodeLoad override
WIP #195 Made ArchEditor, ExecView embeddable
WIP #195 Fixed "super" onNodeLoad call
WIP #195 Updated fab dependency
> Updated fab to wait for territory update Fixes #195

- package.json
- src/visualizers/panels/ExecutionView/ExecutionViewControl.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.js
- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
- src/visualizers/panels/RootViz/RootVizControl.js
- src/visualizers/panels/TextEditor/TextEditorControl.js
WIP #208 Added nodeId checks and logs for selectedObjChanged
WIP #208 Updated webgme-autoviz and webgme-fab
> Updated selObjChanged to check nodeId & updated deps. Fixes #208

- src/plugins/ExecutePipeline/ExecutePipeline.js
WIP #150. Added commits...
WIP #150 cancelled commits...?
WIP #150 Creating jobs serially. Fixed cancelled commits
> Added intermittent commits to pipeline execution. Fixes #150

- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
- src/visualizers/widgets/PipelineEditor/Buttons.js
- src/visualizers/widgets/PipelineEditor/SelectionManager.js
WIP #232 Added jump to op def button in selection
WIP #232 Added returning to pipeline
> Added pivoting btwn op defs and pipeline. Fixes #232

- config/components.json
- src/visualizers/widgets/RootViz/Card.html.ejs
- src/visualizers/widgets/RootViz/RootVizWidget.js
WIP #238 Added root viz icons... Needs ranking
WIP #238 Fixed ordering
WIP #238 Added colors
> Added sorted, colored, root cards w/ icons. Fixes #238

- src/plugins/ExecutePipeline/ExecutePipeline.js
- src/plugins/ExecutePipeline/templates/deserialize.ejs
- src/plugins/ExecutePipeline/templates/main.ejs
> 228 on input nil

- src/plugins/ExecutePipeline/templates/index.js
Long regex to handle this. We should probably handle colors in the future.
> Added regex to remove console colors. Fixes #306 

- README.md
- install.sh
WIP #278 added cloning deepforge repo
WIP #278 updated readme and added more installation logging
WIP #278 added FIXME when merging
WIP #278 Added curl to readme
WIP #278 Fixed var scope
WIP #278 Updated readme
> Added simple install script. Fixes #278

- src/common/viz/NodePrompter.js
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
WIP UX changes...
Added expandable operation creator from fab. Fixes #342
WIP #342 Added nodes to the node prompt
WIP #342 Fixed horizontal positioning
WIP #342 Flexible sized dialog
WIP #342 Added rounded corners
WIP #342 Added padding to cover btn shadow
WIP #342 Hide tooltip and close fab on open
WIP #342 Fixed not closing on "click-and-run"
WIP #342 Re-added cards for RootViz
> Added expandable operation creator from fab. Fixes #342

- src/decorators/OpIntDecorator/EasyDAG/OpIntDecorator.EasyDAGWidget.js
- src/decorators/OpIntPtrDecorator/EasyDAG/OpIntPtrDecorator.EasyDAGWidget.js
WIP #352 Added valid name check for references
> Added test for renaming op input/outputs. Fixes #351

- src/visualizers/panels/ExecutionView/ExecutionViewControl.js
WIP #357 Removing UI if no originId
WIP #357 Checked for null event id
> Added check for null eid and cleaned up territory ui. Fixes #357

- src/visualizers/panels/TextEditor/TextEditorControl.js
- src/visualizers/widgets/TextEditor/TextEditorWidget.js
WIP #366 Fixed activeNode check in TextEditor
> Moved attr check to after node id validation. Fixes #366

- .codeclimate.yml
- .csslintrc
- src/common/globals.js
- src/visualizers/panels/ArchEditor/ArchEditorControl.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
- src/visualizers/widgets/ArchEditor/ArchEditorWidget.js
- src/visualizers/widgets/ArchEditor/styles/ArchEditorWidget.css
WIP #385 Added node icons to arch creator.
WIP #385 Updated for new AddNodeDialog.prompt interface
WIP #385 Added tabs to layers and create layer support
> Added (tabbed) custom layer creation from arch editor. Fixes #385

- src/common/globals.js
- src/visualizers/panels/ArchEditor/ArchEditorControl.js
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
- src/visualizers/widgets/PipelineEditor/Buttons.js
WIP #388 Refactored op -> pipeline pivoting
> Added pivot back to last arch from custom layer. Fixes #388

- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
WIP #390 Added delete button (non-func)
WIP #390 Added deletion func for deleting current node
> Added operation deletion button. Fixes #390

- src/decorators/OpIntDecorator/EasyDAG/OpIntDecorator.EasyDAGWidget.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.EventHandlers.js
- src/visualizers/widgets/OperationInterfaceEditor/OperationInterfaceEditorWidget.js
WIP #171 Adding support for new classes
WIP #171. Fixed "New Class" tooltip
> Added 'Create Class' node in OperationEditor. Fixes #171

- src/common/globals.js
- src/plugins/ImportArtifact/ImportArtifact.js
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
- src/visualizers/widgets/PipelineEditor/PipelineEditorWidget.js
WIP #422 Added upload artifact icon
WIP #422 Added upload artifact functionality
> Added artifact upload from ArtifactLoader. Fixes #422

- src/decorators/OpIntDecorator/EasyDAG/OpIntDecorator.EasyDAGWidget.js
- src/visualizers/panels/OperationInterfaceEditor/Colors.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.EventHandlers.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.js
- src/visualizers/widgets/OperationInterfaceEditor/OperationInterfaceEditorWidget.js
WIP #432 Added basic support for primitive/complex coloring and creation
WIP #432 Added tabs
> Added support for creating primitive types from op editor. Fixes #432

- src/visualizers/Visualizers.json
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
- src/visualizers/panels/MainView/MainViewControl.js
- src/visualizers/panels/MainView/MainViewPanel.js
- src/visualizers/widgets/MainView/ListItem.ejs
- src/visualizers/widgets/MainView/MainViewWidget.js
- src/visualizers/widgets/MainView/NavBar.html
- src/visualizers/widgets/MainView/styles/MainViewWidget.css
- src/visualizers/widgets/MainView/styles/MainViewWidget.css2
- src/visualizers/widgets/MainView/styles/MainViewWidget.scss
- webgme-setup.json
WIP #440 Added MainView
WIP #440 Removed unneeded files
WIP #440 Added basic left bar
WIP #440 Added root node actions
WIP #440 Embedded PipelineIndex
WIP #440 Removed unused js
WIP #440 Removed setTimeout
WIP #440 Fixed some layout issues. css reduction
WIP #440 Added glyphicon
WIP #440 Fixed menu control icon placement, size, color
WIP
WIP #440 Added opening/closing of the nav bar
WIP #440 Added grey background-color
WIP #440 Fixed hide on small screens
WIP #440. Added action buttons
WIP #440 Fixed arch-content list
WIP #440 Removed bullet points
WIP #440 Fixed resize positioning
WIP #440 Increased font size for headers
WIP #440 italic actions
WIP #440 Added some structure for the artifacts
WIP #440 Added download artifact link
WIP #440 Fixed lingering territory rules
> Updated main view to have nav bar and pipeline index. Fixes #440

- src/common/viz/RenameablePanel.js
- src/visualizers/panels/ArchEditor/ArchEditorPanel.js
- src/visualizers/panels/OperationEditor/OperationEditorPanel.js
- src/visualizers/panels/PipelineIndex/PipelineIndexControl.js
WIP #445 Refactoring the panel title renaming
WIP #445 Made arch editor renameable
> Added editable title for architecture. Fixes #445

- src/common/viz/OperationControl.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.EventHandlers.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.js
- src/visualizers/widgets/OperationInterfaceEditor/OperationInterfaceEditorWidget.js
WIP #376 Removed 'Data' from output options
> Added 'Data' to op input options. Fixes #376

- src/visualizers/panels/ArchEditor/ArchEditorControl.js
WIP #78 ~3x speedup in arch editor
WIP #78 Removed unused var
> Optimized the arch editor layer selection. Fixes #78

- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.EventHandlers.js
- src/visualizers/widgets/ArchEditor/ArchEditorWidget.js
- src/visualizers/widgets/OperationInterfaceEditor/OperationInterfaceEditorWidget.js
- src/visualizers/widgets/PipelineEditor/SelectionManager.js
WIP #465 Updated onAddButtonClicked
WIP #465 Updated callbacks for webgme-easydag update
> Updated buttons and methods for webgme-easydag update. Fixes #465

- src/common/viz/Buttons.js
- src/visualizers/widgets/ExecutionView/SelectionManager.js
- src/visualizers/widgets/OperationInterfaceEditor/Buttons.js
WIP #406 Updated some icons
WIP #406 Updated the terminal icon
WIP #406 Updated operation interface icons
WIP #406 terminal -> monitor icon
> Updated icons. Fixes #406

- config/components.json
- package.json
- src/visualizers/Visualizers.json
WIP #479 Updated autoviz version
> Added editors to preload by autoviz. Fixes #479

- src/plugins/ExecutePipeline/ExecutePipeline.js
Improved execution fork name. Fixes #494
> Created better execution fork names. Fixes #494

- install.sh
WIP #395 Added ubuntu/arch detection
WIP #395 added manual nvm loading
WIP #395 Added source post-installation instructions
WIP #395 Added ubuntu/arch detection
> Added ubuntu support to install script. Fixes #395

- src/visualizers/widgets/LogViewer/LogViewerWidget.js
WIP #304 Added scroll to bottom
WIP #304 Added eof detection
> Added tracking EOF for log viewer. Fixes #304

- src/visualizers/panels/TilingViz/TilingVizPanel.js
WIP #502 Removed padding from the tiling viz's panel
> Removed panel padding. Fixes #502

- package.json
- src/visualizers/panels/MainView/MainViewPanel.js
WIP #507 set webgme-autoviz to track master
> Updated the selObjChanged to update pipeline list. Fixes #507

- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.js
- src/visualizers/widgets/OperationInterfaceEditor/Item.js
> Added unused output detection. Fixes #518

- src/common/Constants.js
- src/plugins/ExecuteJob/ExecuteJob.js
- src/visualizers/panels/OperationCodeEditor/OperationCodeEditorControl.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.js
- src/visualizers/widgets/OperationInterfaceEditor/OperationInterfaceEditorWidget.js
WIP #531 Created Constants for lineOffset
WIP #531 Removed 'lineOffset' from visible op node attr
> Hide 'lineOffset' in operation interface editor. Fixes #531

- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecutePipeline/metadata.json
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
WIP #363 Fixed plugin execution on server
WIP #363 Changed primary execution env to the server
WIP #363 Set initial pipeline execution to be on server
> Moved default execution management to server. Fixes #363

- bin/.eslintrc.yml
- bin/config.json
- bin/deepforge
- package.json
- test/cli/cli.spec.js
WIP #526 Added update command
WIP #526 Added start command
WIP #488 Added mongo detection
WIP #526 Added torch checking & installation
WIP #526 Added help if no args and 'mongodb not installed' msg
WIP #526 Made mongo check into a promise
WIP #526 Made mongodb dir customizable
WIP #526 Config getting/setting
WIP #526 Fixed mongodb starting/checking
WIP #526 Added --torch to update cmd
WIP #526 Added uninstall command
WIP #526 Added --server opt to update and updated package.json
WIP #526 Added eslintrc for bin scripts
WIP #526 minor description fix
> Added deepforge management cli. Fixes #526

- bin/deepforge
- package.json
- test/cli/cli.spec.js
> Replaced unlink w/ rimraf. Fixes #549

- bin/deepforge
- install.sh
WIP #546 Updated install script
WIP #546 Changed install url temporarily
WIP #546 Removed torch install from install script
WIP #546
WIP #546 cd -> process.chdir
> Updated install script for cli. Fixes #546

- src/plugins/ExecuteJob/ExecuteJob.js
- src/visualizers/panels/LineGraph/LineGraphControl.js
- src/visualizers/widgets/LineGraph/LineGraphWidget.js
WIP #562 Added cleaning the ansi codes from metadata cmds
WIP #562 Fixed point parsing
WIP #562 Cleaning x,y point text
> Removed special characters during metadata cmds. Fixes #562

- src/plugins/ExecuteJob/ExecuteJob.js
- src/visualizers/panels/ClassCodeEditor/ClassCodeEditorControl.js
- test/plugins/ImportTorch/ImportTorch.spec.js
WIP #412 Added inheritance setting/unsetting based on code
WIP #412 Fixed ordering of the base class loading
> Added custom class inheritance support. Fixes #412

- src/visualizers/widgets/LogViewer/LogViewerWidget.js
WIP #582 Added better ansi regex
WIP #582 Fixed infinite loop
> Added more flexible ansi code detection. Fixes #582

- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecutePipeline/ExecutePipeline.js
WIP #591 Added notification on fork to ExecuteJob
WIP #591 Fixed fork name creation
> Added notification on fork to ExecuteJob. Fixes #591

- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecutePipeline/ExecutePipeline.js
WIP #596 Added quotes around job, exec, branch for consistency
> Added "complete" notification if exec forked. Fixes #596

- config/config.base.js
It is labeled as a "major" issue bc of it's impact (not it's trivial amount of code)
> Enabled autoMerge. Fixes #332 Fixes #346

- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
WIP #617 moved client edits out of promise
WIP #617 Made 'isRunning' more robust
WIP #617 Fixed client calls
> Update attributes on cancel job. Fixes #617

- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecuteJob/templates/start.ejs
> Added explicit data download on worker. Fixes #624

- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecuteJob/templates/deserialize.ejs
- src/plugins/ExecuteJob/templates/start.ejs
WIP #616 Added cache dir if doesn't exist
WIP #616 Removed data from execution files
WIP #616 Added pointer files to data download
WIP #616 Fixed symlink creation
> Added caching support to workers. Fixes #616

- src/plugins/ImportTorch/ImportTorch.js
- test/plugins/ImportTorch/ImportTorch.spec.js
> Added implicit require 'nn' to ImportTorch. Fixes #644

- bin/config.json
- bin/deepforge
- bin/envConfig.json
- config/config.base.js
WIP #639 Added config schema
WIP #639 Added blob.dir config value
> Added blob.dir configuration. Fixes #639

- bin/config.json
- bin/deepforge
- bin/envConfig.json
- bin/start-local.js
- package.json
- src/plugins/ExecuteJob/templates/start.ejs
WIP #638 Added config schema
WIP #638 Added default cache location
WIP #638 Added useBlob fn-ality
WIP #638 Added type checking
WIP #638 Fixed config merge issue
WIP #638 Create worker cache parent dir if needed
> Added configurable worker.cache.dir and worker.cache.useBlob. Fixes #638

- src/plugins/CreateExecution/CreateExecution.js
- src/plugins/ExecutePipeline/ExecutePipeline.js
WIP #660 Added more logs
WIP #660 Added more logs during execution creation
WIP #660 Added more logging for starting executions
> Added more logging to better debug failures in the future. Fixes #660

- src/decorators/OpIntPtrDecorator/EasyDAG/OpIntPtrDecorator.EasyDAGWidget.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.EventHandlers.js
- src/visualizers/panels/OperationInterfaceEditor/OperationInterfaceEditorControl.js
- src/visualizers/widgets/OperationInterfaceEditor/Item.js
- src/visualizers/widgets/OperationInterfaceEditor/OperationInterfaceEditorWidget.js
WIP #690 Added viz feedback about unknown type
WIP #690 Starting to add ref type setting
WIP #690 Added click fn-ality. still has bad error tooltip
WIP #690 Replaced baseName tooltip on ref set
> Added unknown ref type error and setting. Fixes #690

- config/components.json
- package.json
WIP #662 Set cachePrefix for path storage
WIP #662 Updated breadcrumbheader version
> Updated breadcrumb header. Fixes #662

- src/plugins/ExecuteJob/ExecuteJob.js
WIP #298 Adding progress bar support...
WIP #298 Updated stdout logs for \r support
> Added support for \r in job logs. Fixes #298

- src/visualizers/widgets/LogViewer/LogViewerWidget.js
- src/visualizers/widgets/TextEditor/TextEditorWidget.js
WIP #696 Added 5 lines to bottom of log file
WIP #696 Set scroll margin to 75px (from bottom)
> Added margin to bottom of log viewer. Fixes #696

- src/decorators/JobDecorator/EasyDAG/JobDecorator.EasyDAGWidget.js
WIP #574 Added comments for modification locations
WIP #574 Added ArtifactLoader check
WIP #574 Set ArtifactLoader name to the pointer value
> Set the ArtifactLoader name to target in execution view. Fixes #574

- src/common/viz/Execute.js
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
- src/visualizers/panels/ForgeActionButton/PluginConfig.json
- src/visualizers/panels/JobEditor/JobEditorPanel.js
- src/visualizers/panels/OperationCodeEditor/OperationCodeEditorControl.js
- src/visualizers/widgets/OperationCodeEditor/OperationCodeEditorWidget.js
WIP #641 Added key listener for floating action button
WIP #641 Ignored shift+enter in code editor
WIP #641 Fixed shift-enter to restart job
WIP #641 Added shift-enter for execution view
> Added shift-enter to restart jobs/execs/etc. Fixes #641

- src/common/globals.js
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
- src/visualizers/panels/MainView/MainViewControl.js
- src/visualizers/panels/MainView/MainViewPanel.js
WIP #681 Added comments for work to be done and some place loading support
WIP #681 changed places to use promises
WIP #681 Updated MainView to use places promises
> Updated DeepForge.places to use promises. Fixes #681

- src/common/utils.js
- src/plugins/GenerateArchitecture/GenerateArchitecture.js
- src/visualizers/panels/ExecutionIndex/ExecutionIndexControl.js
- src/visualizers/widgets/ExecutionIndex/ExecutionIndexWidget.js
WIP #675 Added execIds to executions in ExecIndex
WIP #675 Updated line name if multi execs showing
WIP #675 show execution abbreviation if needed
> Added exec abbreviations when multiple selected in index. Fixes #675

- bin/deepforge
- test/cli/cli.spec.js
WIP #705
WIP #705 Fixed error detection on torch install
> Improved error handling on torch install. Fixes #705

- src/visualizers/panels/TextEditor/TextEditorControl.js
- src/visualizers/widgets/DeserializeEditor/DeserializeEditorWidget.js
WIP #744 Fixed name setting on every save
WIP #744 Placed 'saveTextFor' in a transaction
> Improved name change detection and added transaction. Fixes #744

- src/plugins/CreateExecution/CreateExecution.js
- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecutePipeline/ExecutePipeline.js
WIP #682 Added cache update on merge
WIP #682 Updating cache, rootNode, activeNode on merge
WIP #682 Changed to fast-forward
WIP #682 Fixed merge errors w/ multi executions
> Added fast-forward to ExecutePipeline on merge. Fixes #682

- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
- src/visualizers/widgets/PipelineEditor/PipelineEditorWidget.js
This fixes the issue when referencing architectures but doesn't future proof it against other types so I made an issue: https://github.com/dfst/webgme-easydag/issues/149 for a generic solution as well
> Added architecture creation reference. Fixes #757

- app.js
- src/plugins/CheckLibraries/CheckLibraries.js
WIP #788 Clear the hash info on server start (in case blob changed)
WIP #788 Added version info to hash file.
> Stored lib version w/ hash and clear on start. Fixes #788

- config/config.base.js
- config/config.local.js
WIP #752 Updated config.local.js setting
> Preserve jobs on server restart. Fixes #752

- install.sh
Also removed mongodb installation from install script
> Added check for compatible node version. Fixes #552

- config/config.test.js
- config/config.webgme.js
- package.json
- src/common/Constants.js
- src/common/JobLogsClient.js
- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecutePipeline/ExecutePipeline.js
- src/routers/JobLogsAPI/JobLogManager.js
- src/routers/JobLogsAPI/JobLogsAPI.js
- src/visualizers/panels/Footer/FilteredNotificationWidget.js
- src/visualizers/panels/Footer/FooterPanel.js
- src/visualizers/panels/LogViewer/LogViewerControl.js
- test/common/JobLogsClient.spec.js
- test/globals.js
- test/routers/JobLogsAPI.spec.js
- webgme-setup.json
WIP #785 Initial router commit
WIP #785 Added the log manager api
WIP #785 Added some comments for needed updates
WIP #785 Fixed typo in export
WIP #785 Added basic fn-ality to JobLogsClient
WIP #785 Added tests for the log router
WIP #785 uri encode project, branch. Updated viz to use the log-storage
WIP #785 Fixed updating on stdout update
WIP #785 Filtered out stdout update msgs from the notification widget
WIP #785 Added stdout save on canceled
WIP #785 Added tests for the joblogsclient
WIP #785 Moved job logs client to src/common
WIP #785 Added forking support to api
WIP #785 Added fork support for the job log client
WIP #785 Fixed flashing on canceled job
> Added log-storage for running jobs. Fixes #785

- package.json
- src/common/utils.js
- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecuteJob/templates/deepforge.ejs
- src/routers/JobLogsAPI/JobLogManager.js
WIP #802 Added express dependency
WIP #802 Added carriage return check to log-storage api
WIP #802 Fixed saving for graphs, images
Also fixed bug when using xlua progress bar w/ graphs
> Fixed graph updating, express dependency Fixes #802

- src/plugins/ExecuteJob/templates/deepforge.ejs
- src/plugins/ExecuteJob/templates/main.ejs
- src/visualizers/widgets/TextEditor/deepforge.json
WIP #798 Updated deepforge completer
> Added deepforge.initialize(). Fixes #798

- src/visualizers/panels/PipelineIndex/PipelineIndexControl.js
~~This works when the executions have been loaded/viewed at least once. If not, they will not be deleted due to https://github.com/webgme/webgme/issues/1161~~
It has been updated to first load the execution nodes then delete them
> Delete executions w/ pipeline. Fixes #773

- src/common/Constants.js
- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecuteJob/templates/deepforge.ejs
- src/plugins/ExecuteJob/templates/start.ejs
- src/visualizers/widgets/ImageViewer/ImageViewerWidget.js
WIP #799 Added deepforge.Image basics
WIP #799 deepforge.Image creates image
WIP #799 Fixed the image id creation
WIP #799 Don't reset zoom on image update
WIP #799 Added support for updating image names
> Added deepforge.Image w/ update, title. Fixes #799

- src/routers/JobLogsAPI/JobLogManager.js
- test/routers/JobLogsAPI.spec.js
WIP #813 Check if file exists before copy
WIP #813 Added test
> Better log-storage error handling on fork. Fixes #813

- src/decorators/OperationDecorator/EasyDAG/OperationDecorator.EasyDAGWidget.js
- src/visualizers/widgets/PipelineEditor/PipelineEditorWidget.js
> Static port position regardless of amt showing. Fixes #864

- docker-compose.yml
steps: `docker-compose pull && docker-compose up` 
shutdown: `docker-compose down`
> Added docker-compose file

- config/components.json
- config/config.default.js
Also added comment for simplifying enabling user accounts
> Updated header config for user accounts. Closes #1057

- src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
- src/visualizers/panels/ResourceIndex/ResourceIndexControl.js
- src/visualizers/widgets/PipelineEditor/PipelineEditorWidget.js
copied drag n drop capability into PipelineEditor,  PipelineIndex, ResourceIndex
> added dragndrop for certain visualizers.

- src/plugins/GenerateJob/templates/main.ejs
Added logging of signals received by job processes
> Log signals received by job process. Closes #1207

- src/common/viz/ConfigDialog.js
- src/common/viz/Execute.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
This includes using "name" instead of "id" to conform to WebGME
convention w/ options.
> Update ConfigDialog to show displayName. Fixes #1314

- src/common/storage/backends/StorageBackend.js
- src/plugins/CreateExecution/CreateExecution.js
- src/plugins/ExecuteJob/ExecuteJob.js
- src/plugins/ExecutePipeline/ExecutePipeline.js
- src/visualizers/panels/ForgeActionButton/Actions.js
- src/visualizers/panels/ForgeActionButton/ForgeActionButton.js
This PR contains some code clean up that I had made locally while working on other issues. Specifically, this contains:
- Remove old commented out code
- Use built in JS instead of regex
- Use async-await, const
(As this is just cleaning up code and trying to stay ahead of technical debt, this PR does not have an associated issue.)
> Misc code clean up and refactoring

- src/common/compute/backends/local/Client.js
This updates the local compute backend to store results on disk rather than in memory and in the GME blob.
> Update local compute backend to keep results on disk. Close #1365

- src/common/storage/backends/sciserver-files/Client.js
This also includes the removal of some dead code.
> Print SciServer Files response text on error. Closes #1380

- src/visualizers/panels/ArtifactIndex/ArtifactIndexControl.js
- src/visualizers/widgets/ArtifactIndex/ArtifactIndexWidget.js
- src/visualizers/widgets/ArtifactIndex/ModelItem.js
This updates the artifact index to create urls lazily. This is required as a prerequisite for #1415 and is related to #1414
> Create download URL lazily from artifact index. Closes #1416

- .github/workflows/docker-build.yml
- Dockerfile
- environment.yml
On push to master, we will publish a docker image for `deepforge` server to `docker-hub`. (Depends on #1467).
> Git Action to publish latest docker image to Docker Hub (Closes #1475)

- src/plugins/ImportLibrary/ImportLibrary.js
- src/plugins/UploadSeedToBlob/UploadSeedToBlob.js
This PR includes updates to a couple of the plugins to use async/await syntax rather than promises.
> Refactor library update/seed upload to async/await.

- src/plugins/ImportLibrary/ImportLibrary.js
> Generate valid branch names on collision. Fixes #1507

- docker-compose.yml
> Mount token keys outside WORKDIR in docker-compose.yml. Closes #1549

- src/common/viz/FigureExtractor.js
- src/common/viz/Utils.js
- src/visualizers/panels/ExecutionIndex/ExecutionIndexControl.js
- src/visualizers/panels/PlotlyGraph/PlotlyGraphControl.js
- src/visualizers/widgets/PlotlyGraph/PlotlyDescExtractor.js
- src/visualizers/widgets/PlotlyGraph/PlotlyGraphWidget.js
1. Move node data extraction code to a separate FigureExtractor.js
2. Move PlotlyDescExtractor to the PlotlyGraphWidget
3. Refactor common code into functions
> Refactor PlotlyDescExtractor (Closes #1544)

- package-lock.json
- package.json
This updates the webgme version to the latest version. Not really an ideal solution but we require features only available on the bleeding edge of webgme.
> Update webgme version. Fixes #1580

- .deployment/dev-entrypoint.sh
Removes `local` compute from deployment docker images before starting.
> Disable local compute in deployment (Closes #1605)

- .github/workflows/npm-publish.yml
- utils/install-conda.sh
> Publish deepforge to npm on release. (Closes #1612)

- src/common/viz/ConfigDialog.js
This is a first pass at this and is a somewhat naive implementation as it would be better to be able to encrypt authentication information on the server (https://github.com/webgme/webgme-engine/pull/200)
> Save/load previous settings in config dialog. Closes #1638

- src/common/viz/ConfigDialog.js
An example of this can be seen in https://github.com/deepforge-dev/deepforge/pull/1630#issuecomment-614701975
> Use metadata name field by default (if available). Close #1658

- src/common/storage/backends/sciserver-files/Client.js
> Add better error logging for SciServer Files. Fixes #1668

- src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh
It's worth noting that this uses `node` for parsing the JSON files (avoiding any additional external dependencies).
> Read command, args from executor_config.json. Closes #1700

- src/plugins/TwoPhaseCommit/CreatedNode.js
- src/plugins/TwoPhaseCommit/TwoPhaseCore.js
- test/unit/plugins/TwoPhaseCommit/TwoPhaseCommit.spec.js
- test/unit/plugins/TwoPhaseCommit/TwoPhaseCore.spec.js
This still needs some tests but otherwise should be all set!
> Add additional functions to TwoPhaseCore. Closes #1706

- src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh
This still needs some testing...
> Install plotly to sciserver compute image. Fixes #1826

- src/common/plugin/ExecutionHelpers.js
Other resources can be mistaken for the input/output containers resulting in the node snapshot being created incorrectly.
> Ignore other node children when fetching IO containers. Fixes #2000

- config/components.json
- src/visualizers/widgets/Sidebar/NavBar.html
- src/visualizers/widgets/Sidebar/SidebarWidget.js
Reverts deepforge-dev/deepforge#2032
> Revert "Disable interactive workspace for stable release. Close #2031"
