src/decorators/DcOpDecorator/DcOpDecorator.js
src/decorators/DcOpDecorator/EasyDAG/DcOpDecorator.EasyDAGWidget.css
src/decorators/DcOpDecorator/EasyDAG/DcOpDecorator.EasyDAGWidget.js
src/plugins/ExecutePipeline/LocalExecutor.js
src/seeds/minimal/minimal.webgmex
src/seeds/pipeline/pipeline.webgmex
src/seeds/project/project.webgmex
src/visualizers/panels/PipelineEditor/PipelineEditorControl.js
webgme-setup.json

WIP #166 Added ArtifactLoader to seeds
WIP #166 Added OpIntDecorator
WIP #166 Filtered out the meta data nodes
WIP #166 Added node creation/base change on pointer set
WIP #166. Fixed output node creation
WIP #166 Added ArtifactLoader to LocalExecutor

Added ArtifactLoader. Fixes #166

---

src/plugins/ExecutePipeline/templates/index.js

Reverts dfst/deepforge#307
This was preventing the real time (+/- 1.5 s) logging. This should probably be fixed in the browser and set the colors correctly

Revert "Added regex to remove console colors. Fixes #306 "

---

src/visualizers/panels/OperationEditor/OperationEditorPanel.js
src/visualizers/widgets/OperationCodeEditor/OperationCodeEditorWidget.js

WIP #380 Added editable title
WIP #380 Updated the operation header comment

Added editable operation title & better header comment. Fixes #380

---

src/common/lua.js
src/plugins/ImportTorch/ImportTorch.js
src/plugins/ImportTorch/nn.js
test/test-cases/code/googlenet-setters.lua

WIP #386 Added googlenet-setters for testing error messages

Added meaningful error if retrieving nil val from layer. Fixes #386

---

src/plugins/ExecuteJob/ExecuteJob.js

Added a `run.sh` script to be used for reproducing jobs locally. `run.sh` is a bash script which will download the data from the deepforge server and then run the operation code. After a failed execution, the execution files can be downloaded from the web ui. Then, after unzipping and changing into the unzipped directory, the job can be replicated with:
```
DEEPFORGE_URL=http://localhost:8888 bash run.sh
```
If running deepforge on a remote machine (rather than locally), the `DEEPFORGE_URL` value should be updated accordingly

Added run.sh script to execution files. Fixes #818

---

package.json

Updating webgme fixed this issue: https://github.com/webgme/webgme/issues/1145. If there are problems w/ larger files/slower networks, the server upload timeout can be adjusted (or exposed in the cli config)

Updated webgme version to v2.6.0

---

src/decorators/OpIntDecorator/EasyDAG/OpIntDecorator.EasyDAGWidget.js

Previously, this was causing issues opening attributes with display names that differed from the actual name (such as converting "_" to " " in the visual editor).

Fixed edit attribute name selection for editing. Fixes #1142

---

src/plugins/ExecuteJob/ExecuteJob.js
src/plugins/GenerateJob/templates/start.ejs

This includes a workaround for https://github.com/webgme/executor-worker/issues/12 (https://github.com/deepforge-dev/deepforge/compare/1205-exit-code-null?expand=1#diff-ff6284b0c0e9936d7ea0b95ae89bb23cR229)

Handle null exit codes and no stdout. Fixes #1205

---

src/plugins/GenerateJob/GenerateJob.js

Check the environment using the `isBrowser` flag from requirejs instead of checking for WebGMEGlobal as this can exist in the automated tests.

Updated NodeJS/browser exec env detection. Fixes #1212

---

src/common/compute/backends/ComputeClient.js
src/common/compute/backends/gme/Client.js
src/common/compute/backends/local/Client.js
src/plugins/ExecuteJob/ExecuteJob.js
src/plugins/GenerateJob/GenerateJob.js

Removed `getOutputHashes` in favor of `getDebugFilesHash` and `getResultsInfo`. This also requires `getConsoleOutput` to work both when the job is running and after it completes.

Update getOutputHashes -> {getDebugFilesHash,getResultsInfo} Fix #1330

---

config/components.json
src/common/compute/backends/sciserver-compute/Client.js
src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh
src/common/compute/backends/sciserver-compute/metadata.json
src/common/compute/index.js
src/plugins/GenerateJob/templates/utils.build.js

This PR adds an initial version of a compute backend for SciServer (using the jobs API). However, this does not include support for:
- Uploading files to scratch volumes instead of persistent storage volumes #1349 
- ~~Debug files support (downloading the files to run locally)~~
- Compute dashboard (it would be nice to at least link to the SciServer Jobs dashboard - preferably with a filter for all the deepforge jobs.) #1350 
- Generating code for an entire pipeline #1351
Additionally, this exposed an issue with the GME storage backend as the client currently assumes it is running on same machine as the server. This needs to be fixed so the job running remotely can upload the results to the WebGME blob hosted by DeepForge (when using this backend, of course).

Add initial version of SciServer compute backend. Closes #1309

---

src/visualizers/panels/ExecutionIndex/ExecutionIndexControl.js
src/visualizers/widgets/PlotlyGraph/PlotlyGraphWidget.js

To Fix #1363, This PR Updates the plotly graph widget to have a default text and not throw an error on `ExecutionIndex` Widget.

Add default text for Executions with no Metadata. Fixes #1363.

---

src/common/storage/backends/sciserver-files/metadata.json
src/visualizers/panels/ArtifactIndex/ArtifactIndexControl.js
src/visualizers/widgets/ArtifactIndex/ArtifactIndexWidget.js

This also adds the `isAuth` key to the storage configuration options which is used to designate configuration options for authentication. These options are provided to the user when downloading or deleting the data as well.

Prompt user for auth on artifact delete, download. Closes #1422, #1415

---

src/common/storage/backends/StorageClient.js
src/common/storage/backends/sciserver-files/Client.js
src/plugins/GenerateJob/GenerateJob.js
src/plugins/GenerateJob/templates/index.js
src/plugins/GenerateJob/templates/run-debug.js
src/visualizers/widgets/ArtifactIndex/ArtifactIndexWidget.js

This also updates the SciServer Files storage adapter to use the default implementation.
One downside of this approach is that it does not know when the URL is no longer required to be active. As a result `revokeObjectURL` is never called so blob URLs will be maintained until the document is unloaded. For more info, check out https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL.

Add default impl for getDownloadURL using the browser blob. Close #1425

---

src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh

This adds the aws-sdk dependency to the sciserver compute backend. Currently, this is the only compute backend with explicit dependencies installed as part of the process.
It would be good to improve how compute dependencies are handled but this adds the aws-sdk to the compute dependencies in their current state.

Add aws-sdk to sciserver compute backend. Closes #1464

---

.github/workflows/docker-build.yml
Dockerfile.kitchensink

Builds on top of #1479 to create a `kitchen-sink` Docker image for deepforge server.
For now it is manually installing dependencies for deepforge-keras.  Should be changed when #1466 is resolved. Currently, pinpointing `tensorflow==1.14` and `keras==2.2.5` (https://github.com/deepforge-dev/deepforge-keras/issues/149) should also make some changes here.

Add Docker image with extensions installed and publish it to docker hub. Closes #1484

---

bin/deepforge
package.json
utils/conda-utils.js

This PR removes references to old environment.yml file. This also includes removing the execution of conda-utils as a binary in the postinstall script as this is updated in #1514

Removed references to old env file. Closes #1520

---

test/integration/StorageBackends.spec.js

I generally don't like adding retries to tests but, unfortunately, some of these storage backends are outside our control...

Add retries to storage adapter integration tests. Fixes #1575

---

src/routers/ExecPulse/ExecPulse.js

This removes the strict authentication from the heartbeat endpoint. Not the ideal solution but should be effective and isn't a big security concern.

Remove auth from heartbeat endpoint. Fixes #1594

---

.deployment/README.md
.deployment/deploy-deepforge
.deployment/docker-compose-overrides.yml
.dockerignore
.github/workflows/docker-build.yml
.gitignore

Move deployment script to this repo and add `.deployment` directory to `.dockerignore`.
See https://github.com/deepforge-dev/deepforge/runs/561470471. For a successful action build.

Move Deployment Script to the Repository (Closes #1596)

---

.deployment/deploy-deepforge
src/visualizers/widgets/PlotlyGraph/PlotlyDescExtractor.js

1. Calculate tighter margins necessity for plots
2. Use smaller fonts for x, y and z-label
Same plot as presented in #1450, rendered from this branch.

Fix bad formatting of subplots title. Closes #1450

---

src/common/storage/backends/StorageClient.js
src/common/storage/backends/gme/Client.js
test/unit/common/storage/backends/gme/Client.spec.js

This ensures the server port is set to 80 if omitted from `DEEPFORGE_HOST`.

Improved server port detection in GME storage client. Fixes #1629

---

src/common/compute/backends/sciserver-compute/metadata.json
src/common/storage/backends/sciserver-files/metadata.json

Here is an example of the resulting password field:

Hide sciserver password. Closes #1637

---

.travis.yml
src/common/compute/backends/sciserver-compute/Client.js
src/common/compute/backends/sciserver-compute/metadata.json

Upload execution files to temporary storage. Closes #1349

---

test/unit/common/OperationCode.spec.js
test/unit/test-cases/operations/numeric-attr.py

This PR adds a test for numeric attributes that was added when checking out an issue in a different feature branch. As this test did not find the error, I did not include it in the feature branch.
I am opening the PR here since this test could be useful in the future to prevent regressions.

Add test for numeric attributes in operations.

---

src/common/globals.js
src/visualizers/panels/ForgeActionButton/ForgeActionButton.js

Register actions for action button. Closes #1741

---

.deployment/docker-compose-overrides.yml
docker/docker-compose.yml

Moved the `DEEPFORGE_HOST` environment variable to the deployment overrides. It was initially included there as a bit of an example as it is required to be overwritten before using some of the compute backends. However, it is easy to overlook when spinning up a local instance to test it out and checking `.deployment/docker-compose-overrides.yml` should provide a reasonable example if someone is looking for an example of how to configure a full-fledged custom deployment.

Remove deployment env variables from docker-compose. Fixes #1755

---

src/visualizers/panels/Sidebar/SidebarPanel.js

This is a workaround for #1759. Ideally, this issue will be fixed with the approach taken in #1767. However, that exposed a bug in webgme-engine and is currently blocked. As #1759 is blocking #1747 (which in turn is blocking #1694), I am opening this temporary workaround so we don't have 3 different PRs blocked by the webgme-engine issue (https://github.com/webgme/webgme-engine/issues/222).
This PR changes the application of updates to be applied serially. Once the library updates have been applied, it waits a short amount of time to (hopefully) allow the changes to take effect. Then it runs the migrations using the ApplyUpdates plugin.

Suboptimal workaround for forking when applying updates.

---

src/common/plugin/GeneratedFiles.js
src/common/plugin/LocalExecutor.js
src/plugins/GenerateJob/templates/run-debug.js
src/plugins/GenerateJob/templates/start.js
src/routers/InteractiveCompute/job-files/start.js
utils/build-job-utils.js

This commit adds stream support function added in #1702 for pipeline
execution as well as Interactive Compute router. build job utils
now uses webgme-engine module in webgme/node_modules. This will
add the support for streams in blobclient.

Use stream functions in pipelines. (Closes #1777)

---

src/common/compute/backends/sciserver-compute/Client.js
src/common/compute/backends/sciserver-compute/files/prepare-and-run.sh

This decreases the execution time of a sample benchmarking operation from 53 seconds to 15 seconds. I am unsure why it is still taking 15 seconds but this is still a significant improvement.

Use DeepForge image rather than "SciServer Essential". Closes #1822

---

src/common/storage/backends/gme/Client.js
src/common/storage/backends/gme/metadata.js
src/common/storage/backends/gme/metadata.json
src/common/storage/index.js
src/common/viz/StorageHelpers.js

There is one remaining update that would be good to have:

Add auth to config for gme blob. Fixes #1645

---

src/routers/JobOriginAPI/JobOriginAPI.js

This is not an ideal long term fix as this should be changed to fit with the compute adapters better (related to https://github.com/deepforge-dev/deepforge/issues/1830). However, this should work in the meantime until the JobOriginAPI is updated.

Remove authentication from JobOriginAPI. Fixes #1853

---

src/plugins/ExecuteJob/ExecuteJob.Metadata.js

Still needs some digging but I found that the following find function's 
https://github.com/deepforge-dev/deepforge/blob/974e833773f2494eb01d54fb3f458614a5711136/src/plugins/ExecuteJob/ExecuteJob.Metadata.js#L105-L106
condition is always truthy. This will thus override any other graphs that were created.

Support for multiple plots in same operation (Closes #1975)

---

config/config.extensions.js

webgme apps appear to mutate the same, cached config. This is mostly fine except for when we are adding an extra key to the config and then it is validated when a dependency loads the webgme config. In this case, the addition of the extension info should not mutate the original.

Ensure config "extensions" do not mutate the cached config. Fix #1985

---

bin/deepforge

Perhaps this is too much help info? I think it should be all useful but would be open to thoughts/comments...

Add more helpful error on misconfigured conda env. Closes #1897

---

src/visualizers/panels/ForgeActionButton/ForgeActionButton.js

This may not be the ideal way to handle this (preferably we would ensure the node can always be loaded) but there currently isn't a mechanism for notifying the floating action button of the project change. This will work in the meantime.

Return [] if node cannot be loaded. Fixes #1991

---

src/common/viz/ConfigDialogEntries/CustomConfigEntries.js

When the dropdown was programmatically refreshed after logging into SciServer, the widget's value was not correctly set (as programmatic updates to HTML elements don't trigger the `onchange` handler). As a result, the username being used was "Link account...". This has been updated to explicitly set the value for the widget.

Update in-memory value on dropdown refresh. Fixes #2047
